### ISSUE TITLE
Differences between defaults and conda-forge

### ISSUE THREAD

**Issue by jaimergp** [AnacondaRecipes/conda-standalone-feedstock#11]
Hey folks, I am taking a look at how conda-forge's conda-standalone differs from defaults', and I found about the following items:

Menuinst patches (we can upstream them if needed):

- https://github.com/AnacondaRecipes/conda-standalone-feedstock/pull/9. Is this a critical patch? Can you provide more details about why is it needed?
- [`root_prefix = prefix`](https://github.com/AnacondaRecipes/conda-standalone-feedstock/pull/8/files#diff-b07904245f4bc6f09a1dc20ead429abac860006a976aca31aecb68f9eac5bf85R9). Same, should we upstream this or is this patch only for conda-standalone processes though?

Others:

- [`certifi` data files](https://github.com/AnacondaRecipes/conda-standalone-feedstock/pull/8/files#diff-15f87d468dbc89f21f53b27b448835b508ee11a2404582f47dfe107054f24433R12-R13). Is this related to certificate stuff?
- Why are you [pinning `pyinstaller` to 5.6.2](https://github.com/AnacondaRecipes/conda-standalone-feedstock/pull/8/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR36)?

cc @marcoesters

**Comment by jaimergp** [comment]
(Sorry for the duplicate question, I found more stuff and thought it would be better to have the discussion in a single place).

**Comment by marcoesters** [comment]
To answer your questions:

>  Add patch to remove capitalization of DISTRIBUTION_NAME #9. Is this a critical patch? Can you provide more details about why is it needed?

Just for the record: https://github.com/AnacondaRecipes/conda-standalone-feedstock/pull/9#issuecomment-1699488704

> [certifi data files](https://github.com/AnacondaRecipes/conda-standalone-feedstock/pull/8/files#diff-15f87d468dbc89f21f53b27b448835b508ee11a2404582f47dfe107054f24433R12-R13). Is this related to certificate stuff?

From my notes back then, we got the following error when building the package

```
    OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /tmp/_MEI7tblMW/certifi/cacert.pem
```

I think `pyinstaller` didn't include `certifi` automatically anymore. This may be resolved now though.

> Why are you [pinning pyinstaller to 5.6.2](https://github.com/AnacondaRecipes/conda-standalone-feedstock/pull/8/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR36)?

Because that's a version that worked and we decided to improve reproducibility by pinning the `pyinstaller` version exactly.

> So it feels that:
>
>    (A) There's a fix that doesn't involve patching menuinst
>    (B) We can ignore that patch because it's not an issue anymore in conda/conda-standalone

I think (B) is the correct answer here.


I think by now, most of the issues should be resolved, except for the `DISTRIBUTION_NAME` capitalization.

**Comment by jaimergp** [comment]
> I think `pyinstaller` didn't include `certifi` automatically anymore. This may be resolved now though.

They have this [certifi hook](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-certifi.py), and [we seem to be using it](https://github.com/conda/conda-standalone/actions/runs/6027521626/job/16352897231#step:5:227):

```
6544 INFO: Loading module hook 'hook-certifi.py' from '$PREFIX/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
6544 DEBUG: Collecting data files for certifi
6546 DEBUG: collect_data_files - Found files: [('$PREFIX/lib/python3.9/site-packages/certifi/py.typed', 'certifi'), ('$PREFIX/lib/python3.9/site-packages/certifi/cacert.pem', 'certifi')]
```

---

So all in all it looks like we are good provided that conda/conda-standalone moves to the upcoming menuinst v2 ([thanks to this PR](https://github.com/conda/menuinst/pull/153)).
